on:
  push:
    branches:
      - master
name: Test, Build and Release apk
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        device:
          - "iPhone 8 (13.5)"
          - "iPhone 11 Pro Max (13.5)"
      fail-fast: true
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install dependencies
        run: make install
      - name: Run lint
        run: make lint
      - name: Run unit tests
        run: make unit_test
      - name: List all simulators
        run: make list_simulators
      - name: Start simulator
        run: |
          UDID=$(make list_simulators | awk -F ' *[][]' -v 'device=${{ matrix.device }}' '$1 == device { print $2 }')
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: Run UI tests
        run: make ui_test
      - name: Build APK
        run: make build_android
      - name: Deploy to internal
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.multei }}
          WITH_V: true
